const blogs = [
  {
    id: 1,
    title: "the G.O.A.T",
    body: "And it takes  nsuscipit follow accepted lightly with  nreprehenderit discomfort may be the entire  nnostrum of the things that happens is that they are extremely",
    description: "to provide or to reject the blind are welcome option to find",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 2,
    title: "that was",
    body: "is existed at the time of life  'Blessed are the pain of her pains, nor condemn nseq they are nothing  nfugiat or not at all the blandishments of pleasure, and the discomfort may rejecting some  nWho, not being due, we may be able to open the man who did not, but there is no",
    description: "to provide or to reject the blind are welcome option to find",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 3,
    title: "those who reject the troubles they exercise that is either",
    body: "and on the right, but  nvoluptatis blinded to the election or  nvoluptatis pains or denouncing any resultant  nmolestiae on his work and wants to hate or",
    description: "to provide or to reject the blind are welcome option to find",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 4,
    title: "it will be blinded",
    body: "rejects any and often experience pleasure  mānsit lot of things to take to provide fault  nquir here the opportunity to do the right bound pain  nFor the pleasure of the outdoor",
    description: "to provide or to reject the blind are welcome option to find",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 5,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 6,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 7,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 8,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 9,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 10,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
];

module.exports = blogs;
