const blogs = [
  {
    id: 1,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 2,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 3,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 4,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 5,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 6,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 7,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 8,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 9,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 10,
    title: "the G.O.A.T",
    body: " some text goes here",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
];

module.exports = blogs;
