const blogs = [
  {
    id: 1,
    title: "the G.O.A.T",
    body: "And it takes  nsuscipit follow accepted lightly with  nreprehenderit discomfort may be the entire  nnostrum of the things that happens is that they are extremely",
    description: "to provide or to reject the blind are welcome option to find",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 2,
    title: "that was",
    body: "is existed at the time of life  'Blessed are the pain of her pains, nor condemn nseq they are nothing  nfugiat or not at all the blandishments of pleasure, and the discomfort may rejecting some  nWho, not being due, we may be able to open the man who did not, but there is no",
    description: "to provide or to reject the blind are welcome option to find",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 3,
    title: "those who reject the troubles they exercise that is either",
    body: "and on the right, but  nvoluptatis blinded to the election or  nvoluptatis pains or denouncing any resultant  nmolestiae on his work and wants to hate or",
    description: "to provide or to reject the blind are welcome option to find",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 4,
    title: "it will be blinded",
    body: "rejects any and often experience pleasure  mānsit lot of things to take to provide fault  nquir here the opportunity to do the right bound pain  nFor the pleasure of the outdoor",
    description: "to provide or to reject the blind are welcome option to find",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 5,
    title: "large and easy",
    body: "in order to follow the rejects of the body, provide in any one of these there is nothing  nmollitia us dare to give annoyance  nperspiciatis of denouncing, and the things which I condemn no one from the  nvoluptatis The sorrows of pain and discomfort he wishes to",
    description: "to provide or to reject the blind are welcome option to find",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 6,
    title: "large and easy",
    body: "I will open the sorrow which was worthy of him,  nfacilis some cases we may be able, when they are to be in character, they receive the  nquaerat welcome the ancestors of the great  nips so that the advantage of this kind of pleasure, or the pain of life",
    description: "to provide or to reject the blind are welcome option to find",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 7,
    title: "do the right pain all the time and denouncing",
    body: "selected for rejecting annoying blind does not happen that small pleasure  naccusamus for him to be happy,  river or pleasures that are beneficial to the incident  nut of convenience",
    description: "to provide or to reject the blind are welcome option to find",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 8,
    title: "the G.O.A.T",
    body: "Or could it be beneficial to the softness of pleasure and pain  niste corrupted by rejecting some of the pleasure  mānsit When choosing snacks and small  nperferendis accepted enhanced further assumed that the builder",
    description: "to provide or to reject the blind are welcome option to find",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 9,
    title: "the G.O.A.T",
    body: "Or could it be beneficial to the softness of pleasure and pain  niste corrupted by rejecting some of the pleasure  mānsit When choosing snacks and small  nperferendis accepted enhanced further assumed that the builder",
    description: "This is a decription",
    image: "image url goes here",
    date: new Date(),
  },
  {
    id: 10,
    title: "soccer world",
    body: "Or could it be beneficial to the softness of pleasure and pain  niste corrupted by rejecting some of the pleasure  mānsit When choosing snacks and small  nperferendis accepted enhanced further assumed that the builder",
    description: "pleasure in pain and often the resilience of mind",
    image: "image url goes here",
    date: new Date(),
  },
];

module.exports = blogs;
